@extends('Boot.master')
@section('title')
<title>Terms & COnditions</title>
@stop
@section('body')
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center margin-bottom-40">
				<div class="page-header">
					<h1 class="text-uppercase">Terms & Condition</h1>
					<hr>
				</div>
			</div>
		</div>
		<div class="row">
			<div><br>
				<p>
					This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
					<br><br>
					This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.boot.com website.
					<br><br>
					Your use of the Website and services and tools are governed by the following terms and conditions as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If You transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with Boot Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with Boot.
					For the purpose of these Terms and Condition, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. Boot allows the User to surf the Website or making purchases without registering on the Website. The term "We" , "Us" , "Our" shall mean Boot Internet Private Limited.
					<br><br>
					When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms and Condition. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms and Condition, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.
					<br><br>
					ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Boot Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.
				</p><br>
			</div>
		</div>
	</div>
</section>
@stop